ARG DB_PATH="/app/jobboard.db"
FROM golang:1.25 AS builder
WORKDIR /app
COPY . .
RUN make scraper

FROM scratch
WORKDIR /app
COPY --from=builder /app/bin/scraper /app/scraper
ENTRYPOINT ["/app/scraper", $DB_PATH]
